# Gunakan image PHP dengan Apache
FROM php:8.1-apache

# Salin semua file proyek ke folder root server Apache
COPY ./public /var/www/html

# Atur izin dan aktifkan modul Apache jika diperlukan
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 755 /var/www/html

# Aktifkan ekstensi PHP yang dibutuhkan
RUN docker-php-ext-install mysqli pdo pdo_mysql

# Port yang digunakan oleh aplikasi
EXPOSE 80
